### PR TITLE
Translate rng faq to german

### PR DESCRIPTION
**Pull request by xMarcell**
I translated the rng faq to german.

### CODE REVIEW

**Comment by Zarel** [comment]
Thanks for this!

I think we should probably wait for #1605 to resolve how we want the original one to be phrased, though.

**Comment by xMarcell** [comment]
Alright Zarel, tell me when #1605 has been resolved, then I can look over this translation again to check, if anything has to be changed

**Comment by Zarel** [comment]
@xMarcell I think there was some miscommunication on #1605. You never responded to the suggested changes. I ended up just making them for you. Can you update this translation with those changes?

**Comment by Zarel** [comment]
ty!

**Pull request merged**
