### PR TITLE
PS Dex: Fix CAPs under Glitch category

### PR DESCRIPTION
**Pull request by EnPassant4264**
Super minor fix only relevant to dex.pokemonshowdown.com

### CODE REVIEW

**Comment by mia-pi-git** [comment]
(Can you give this a clearer name that explains what it does? see our [CONTRIBUTING.md](https://github.com/smogon/pokemon-showdown/blob/master/CONTRIBUTING.md#commit-message-standards) standard)

**Comment by EnPassant4264** [comment]
Are you referring to the commit name or the summary?

**Comment by mia-pi-git** [comment]
The pull request name.

**Comment by EnPassant4264** [comment]
better?

**Review by Marty-D — APPROVED** [review]
Nice catch, thanks! 👍

**Pull request merged**
