### PR TITLE
(fix): hide username on screens smaller than 500px

### PR DESCRIPTION
**Pull request by thisisdylandev**
fix for #1943 

First PR here, so open to constructive feedback on how to better do this, if this is applicable.

### CODE REVIEW

**Comment by DaWoblefet** [comment]
Can you provide screenshots of the new behavior? I have a pretty good idea of what it's supposed to be doing but screenshots are always nice :).

**Comment by thisisdylandev** [comment]
@DaWoblefet yeah, sure thing. Thank you for the quick response!
Screen Shot 2022-05-18 at 8 31 36 AM
Screen Shot 2022-05-18 at 8 32 00 AM
Screen Shot 2022-05-18 at 8 32 14 AM

**Comment by DaWoblefet** [comment]
I personally think this is OK. The only other idea I could think of would be to reduce font-size, or force it to say inside its container and add a text-overflow: ellipsis, or perhaps some combo of the two. 

Can we call the class something more descriptive? Maybe ``username-topbar``?

**Comment by AnnikaCodes** [comment]
I like Wob's idea of using `text-overflow: ellipsis`; it would solve the navigation problems while still making it somewhat possible for users with multiple accounts to tell which alt they are on at a glance.

**Comment by Zarel** [comment]
I think this change is better than nothing, so I'm merging for now.

**Review by Zarel — APPROVED** [review]

**Comment by AnnikaCodes** [comment]
Hi, sorry about the wait to merge this. It should go live today!

**Pull request merged**
