### PR TITLE
Fix Mummy showing duplicate messages on failure

### PR DESCRIPTION
**Pull request by Karthik99999**
https://github.com/smogon/pokemon-showdown/projects/3#card-61195884

### CODE REVIEW

**Comment by Zarel** [comment]
What _should_ happen in this case?

**Comment by Zarel** [comment]
Should Mummy not activate at all? If so, the server shouldn't be sending the Mummy activation.

**Comment by Karthik99999** [comment]
If mummy fails due to something like Protective Pads (which is what the bug report mentions), it should still show the ability activating but nothing else (which requires the server sending the `-activate` message). `kwArgs.ability` is not defined when Mummy should fail, which is why it should be checked here to determine if Mummy’s `changeAbility` text should be shown.

**Comment by Zarel** [comment]
OK, I see. I think this is the correct solution, then.

**Comment by Zarel** [comment]
Thanks!

**Pull request merged**
