### PR TITLE
Fix format display for hidden battles

### PR DESCRIPTION
**Pull request by AnnikaCodes**
This was meant to be done with my original battle privacy PR but I forgot :/

### CODE REVIEW

**Comment by Zarel** [comment]
I hope this doesn't break something...

**Comment by Zarel** [comment]
Oh! I remember why it was like this before! Replays from side servers!

**Comment by Zarel** [comment]
`battle-smogtours-ou-589172398528`

**Comment by AnnikaCodes** [comment]
Doesn't it already handle uploaded replays in a special case?

**Comment by Zarel** [comment]
Yes, it does, this is the special case...

**Pull request merged**
