### PR TITLE
Fix broadcasting /help

### PR DESCRIPTION
**Pull request by mia-pi-git**
:s
(currently attempting to broadcast !help mostly breaks.)

### CODE REVIEW

**Comment by Zarel** [comment]
hrm

**Comment by Zarel** [comment]
I'm not sure what this does

**Comment by Zarel** [comment]
But this does seem more consistent

**Comment by mia-pi-git** [comment]
> I'm not sure what this does

This makes it so you can broadcast !help again - before you couldn't, since this would catch it.

**Pull request merged**
