### PR TITLE
Move Room Owners above Admins in the userlist

### PR DESCRIPTION
**Pull request by AnnikaCodes**

### CODE REVIEW

**Comment by Zarel** [comment]
Thanks! Could you also remove the hardcode for me?

**Comment by AnnikaCodes** [comment]
Sure.

**Comment by Zarel** [comment]
I believe there's also a hardcode in the Preact client which can be removed now.

**Comment by Zarel** [comment]
I got it for you.

**Comment by Zarel** [comment]
I got it for you.

**Comment by AnnikaCodes** [comment]
Thanks.

**Pull request merged**
