### PR TITLE
Muting Features

### PR DESCRIPTION
**Pull request by Distrib-ps**
Pr for https://www.smogon.com/forums/threads/muting-ps-chatrooms.3675505/

### CODE REVIEW

**Comment by Zarel** [comment]
I think the request was asking for per-room notification settings, not global notification settings.

**Comment by Distrib-ps** [comment]
Oh yes mb, i watch during the week.

**Comment by sirKiraUzumaki** [comment]
The best we can do is that a command which will mute the room in the room in which the command is called.

**Comment by tps48** [comment]
With permission from @Distrib-ps , I'm taking over on this and working on a per-room notification setting. When that's finished up, should I make a separate PR?

**Comment by Zarel** [comment]
Looks like this is being superseded by #1706.

We can always reopen this if that falls through.

**Pull request closed without merging**
