### PR TITLE
Teambuilder: Add missing support for importing, unpacking, and dragging & dropping boxes

### PR DESCRIPTION
**Pull request by MacChaeger**

### CODE REVIEW

**Comment by Zarel** [comment]
I'm confused how these changes achieve that?

**Comment by Zarel** [comment]
Oh I think I understand a little.

**Comment by MacChaeger** [comment]
This fix covers the remaining places where `storage` wasn't making a distinction between boxes and regular teams.

**Comment by Zarel** [comment]
Thanks!

**Pull request merged**
