### PR TITLE
Add a custom html tag for namecolors

### PR DESCRIPTION
**Pull request by mia-pi-git**
Pretty sure i did this right? Works in testing. Also not sure if the source should be `src` or just `name` - went with `src` for now.

### CODE REVIEW

**Comment by Zarel** [comment]
I think ideally this should just be `<username>Zarel</username>`.

**Comment by Zarel** [comment]
You could manually specify a separate `name` attribute but it should be optional.

**Comment by mia-pi-git** [comment]
> I think ideally this should just be `<username>Zarel</username>`.

Is this possible in Caja, the way it's set up currently? Looking at how `BattleLog.tagPolicy` works, only the attribs (i.e `src`) are available; not the data in the tag. I may be missing something, though.

**Comment by Zarel** [comment]
After a lot of googling:

1. apparently this is just entirely undocumented. feels great after all the time I was yelled at for having supposedly horrible documentation. -_-

2. looking at the actual source code, yes, it's impossible: https://npmdoc.github.io/node-npmdoc-sanitizer/build/apidoc.html#apidoc.element.sanitizer.makeHtmlSanitizer

I would suggest `<namecolor name="Zarel">Zarel</namecolor>`. It's important not to use `src` because that already has a specific meaning pointing to a URL, and usernames are obviously not URLs.

**Comment by Zarel** [comment]
Well, one thing that's possible is that we could preparse with a regex

```js
str.replace(/<namecolor>([^<]*)</namecolor>/gi, '<namecolor name="$1">$1</namecolor>')
```

But probably more complicated.

**Comment by Zarel** [comment]
```js
str.replace(/<namecolor([^>]*)>([^<]*)</namecolor>/gi, (match, attrs, username) => {
  if (/\bname\s*=\s*"/.test(attrs)) return match;
  const escapedUsername = username.replace(/"/g, '&quot;').replace(/>/g, '&gt;');
  return `<namecolor${attrs} name="${escapedUsername}">${username}</namecolor>`;
})
```

(This will additionally support having other attributes, and also deal with some improperly-escaped usernames.)

**Comment by Zarel** [comment]
Looks good, thanks!

**Comment by Zarel** [comment]
We should probably document PS custom HTML somewhere.

**Pull request merged**
