### PR TITLE
Teambuilder: Fix ability display for Pokemon with Special Abilities and no HA

### PR DESCRIPTION
**Pull request by KrisXV**

### CODE REVIEW

**Comment by Zarel** [comment]
I honestly originally did it that way so it would be possible to tell apart special abilities and hidden abilities.

**Comment by Zarel** [comment]
(It also happened to make the code more concise.)

**Comment by KrisXV** [comment]
We can do what we do with special abilities in /dt and surround it in parentheses if that helps with differentiating them

**Comment by Zarel** [comment]
I like that!

**Comment by KrisXV** [comment]
did

**Pull request merged**
