### PR TITLE
Add backgrounds for gravity, wonder & magic room

### PR DESCRIPTION
**Pull request by Volco**
and re-work pseudo weathers to be a bit more dynamic for mod editing with css

@Zarel I finally got around to making the pr for the thing i brought up in dms over a week ago

Here's what the backgrounds look like in battle, trick room is still the same
image
image
image

### CODE REVIEW

**Comment by EvGym** [comment]
Is there any chance this is going to get merged at any point in the near future?

**Comment by EvGym** [comment]
The changes are super small and we can finally see something other than the same trick room field for everything? Please?

**Comment by Volco** [comment]
@Zarel when you get a chance mind looking at this?

**Comment by AnnikaCodes** [comment]
This looks good to me!

**Pull request merged**
