### PR TITLE
Modified Tera Blast animations

### PR DESCRIPTION
**Pull request by shrianshChari**
Made the animations for the various types of Tera Blast various kinds of beam or blast moves (or in the case of Grass, the closest thing to that). Also changed base Tera Blast to Swift because its animation fits base Tera Blast better than Scald's does.

### CODE REVIEW

**Comment by Zarel** [comment]
Thanks!

**Comment by KrisXV** [comment]
@Zarel why did you merge this? There were numerous things I haven't been able to address yet. Notably, Scald is literally almost identical to the default Tera Blast animation. What's the point of letting others do animations if you won't let them comment when the animations they decided on get changed?

**Comment by KrisXV** [comment]
Here is an easily accessible video by the way:
https://www.youtube.com/watch?v=6LYZwaY1LVI

**Comment by KrisXV** [comment]
Seed Flare is more indicative of the power level that a Grass Tera Blast shows in-game, so I went with that over Energy Ball. Same for other moves like Earth Power over Mud Bomb. Ground Tera Blast being represented by Mud Bomb is laughable and makes it look like it should be a 60-Base Power move.

**Comment by KrisXV** [comment]
@shrianshChari are you in the dev discord? I would have really appreciated if you spoke with me about this before doing this.

**Comment by KrisXV** [comment]
(Also, you would see in the video that Ground Tera Blast is actually indicative of Earth Power more than it is of Mud Bomb)

Tera Blast is not a blast move _at all_ in any sense other than name, so I would have appreciated if some research was done before this PR was made or merged.

**Comment by Zarel** [comment]
> @Zarel why did you merge this? There were numerous things I haven't been able to address yet. Notably, Scald is literally almost identical to the default Tera Blast animation. What's the point of letting others do animations if you won't let them comment when the animations they decided on get changed?

The changes seemed sensible! People keep getting mad at me when I _don't_ merge things! I didn't know animations were your thing now!

**Comment by KrisXV** [comment]
> > @Zarel why did you merge this? There were numerous things I haven't been able to address yet. Notably, Scald is literally almost identical to the default Tera Blast animation. What's the point of letting others do animations if you won't let them comment when the animations they decided on get changed?
> 
> The changes seemed sensible! People keep getting mad at me when I _don't_ merge things! I didn't know animations were your thing now!

I very strongly urge you to watch the video and revert this

**Comment by shrianshChari** [comment]
> @shrianshChari are you in the dev discord? I would have really appreciated if you spoke with me about this before doing this.

My apologies, I honestly thought the PR would get run through multiple people before getting merged. I'm already in the Discord and have done some work on the calc but I didn't realize that move animations were entirely "Kris's domain." 

> (Also, you would see in the video that Ground Tera Blast is actually indicative of Earth Power more than it is of Mud Bomb)
> 
> Tera Blast is not a blast move _at all_ in any sense other than name, so I would have appreciated if some research was done before this PR was made or merged.

After looking at the video, I realized that I had no idea that the Tera Blast animations weren't all just various colored beams. I'd be down to revert this commit for now.

I still think Swift fits un-Tera'd Blast better than Scald tbh.

**Comment by KrisXV** [comment]
> I didn't realize that move animations were entirely "Kris's domain."

You are more than welcome to pullreq changes to the animations, I was mainly aiming my grievances towards the fact it got merged with almost no input at all. That being said, I do think communication is key for something that goes as easily noticed as animations, so in the future, please bring up some ideas in #art or #client in the dev discord before making a pullreq to make sure your work doesn't get reverted from a miscommunication.

**Pull request merged**
