### PR TITLE
Improve errors when using room commands in PMs

### PR DESCRIPTION
**Pull request by AnnikaCodes**
Ideally we can refactor commands to specify whether they apply in PMs, rooms, or both. Is that something that Preact is doing?

### CODE REVIEW

**Comment by Zarel** [comment]
It's not currently being done in the Preact client. I'll let you decide if it should be.

**Comment by Zarel** [comment]
(Also thanks)

**Comment by AnnikaCodes** [comment]
I think it should be; a lot of these commands could work just as well in PMs (e.g. `/user` and `/highlight`). It's not a huge deal though since people can join a room.

**Comment by Zarel** [comment]
What I mean is, feel free to implement a system like this into the Preact client.

**Pull request merged**
