### PR TITLE
Explicitly mark more non-submit buttons with their type

### PR DESCRIPTION
**Pull request by urkerab**
Anywhere where there's a form with more than one button, I added `type="button"` to all the other buttons. (Unless I missed some...) In particular this should fix issue #1717.

### CODE REVIEW

**Comment by Zarel** [comment]
This is a lot of work for something that usually doesn't make a difference. Are you sure it makes a difference here?

**Comment by Zarel** [comment]
I'm pretty sure PS's dispatcher intentionally doesn't require `type="button"`. Issue #1717 probably has to do more with browser compatibility than with `type="button"`. Have you tested it to make sure the difference exists?

**Comment by urkerab** [comment]
It makes a difference for #1717, because we don't want the reveal password button to be the default button, and I thought I should mark other buttons for consistency, otherwise it might cause confusion in future.

**Comment by urkerab** [comment]
It makes a difference for #1717, because we don't want the reveal password button to be the default button, and I thought I should mark other buttons for consistency, otherwise it might cause confusion in future.

**Comment by Zarel** [comment]
Oh, I see! That's valid.

**Pull request merged**
