### PR TITLE
Don't require desktop notifications for disconnections

### PR DESCRIPTION
**Pull request by urkerab**
Requested [here](https://www.smogon.com/forums/threads/3659047/).

### CODE REVIEW

**Comment by Zarel** [comment]
Wouldn't this give two notifications if you have notifications enabled? That seems probably bad...

**Comment by Zarel** [comment]
I thought the `ReconnectPopup` was clear enough, anyway. If a user isn't seeing it, I'm not sure if this will help at all.

**Comment by Zarel** [comment]
The right cure, I think, probably involves writing our own heartbeat system since SockJS's doesn't handle our use-case?

**Comment by urkerab** [comment]
The user isn't seeing it because they don't have the PS! tab selected, and the tab's icon doesn't change for a disconnect.

But you're right about the second notification, so I've removed the duplicate.

**Comment by Zarel** [comment]
The only remaining problem with this is that the Main Menu would glow orange even after you'd dismissed the "disconnected" popup, giving the false impression that you should open the Main Menu and there will be something in there to look at.

I'm not sure if that's something worth fixing, though? I'll let that be your call.

**Comment by urkerab** [comment]
It's useful in case you accidentally dismiss the reconnect popup? It reminds you that you're disconnected and where you can find the Reconnect button.

**Comment by Zarel** [comment]
The main thing is that when you actually click on the big orange "Home" button, you're greeted with nothing. No message about disconnection or anything like that.

I guess the "search battle" button says "Disconnected" with "Reconnect" under it. I suppose that's enough.

**Pull request merged**
