### PR TITLE
Use DexSearch for the teambuilder search engine

### PR DESCRIPTION
**Pull request by Zarel**
This will prevent us from needing to maintain two search engines in the future.

The new DexSearch doesn't have too much in the way of new features so far, but it does show filtered things in categories, and list illegal results in-filter even after sorting.

These are really minor differences, though; the main thing is just that its architecture should make it much easier to maintain, and in particular, to add more filters.

### CODE REVIEW

**Comment by Zarel** [comment]
BEFORE:

image

AFTER:

image

**Comment by Zarel** [comment]
Sorting a filtered result:

BEFORE:

image

AFTER:

image

**Comment by scheibo** [comment]
It seems like this would be useful to repurpose for the formats search dropdown. eg.`[OU], [Singles]` or `[VGC]`. Preferably coupled with buttons to quick apply certain popular filters on mobile.

**Comment by Zarel** [comment]
We have a formats search dropdown?

**Comment by Zarel** [comment]
I'm not confident there'll be no bugs, but whatever, we can fix them live.

**Pull request merged**
