### PR TITLE
Support using form elements to send commands

### PR DESCRIPTION
**Pull request by mia-pi-git**
Might not be the best way to do this, but for some reason the global event listener on `app` didn't work, so i had to trickle it down into ConsoleRoom and HTMLRoom.

### CODE REVIEW

**Comment by Zarel** [comment]
I guess you don't know how event bubbling/capture works. It's okay, the way we used Backbone's event system led to a huge mess, I tried to clean it up but gave up. Your solution works and that's the important part, I'm going to leave it alone.

**Comment by PartMan7** [comment]
Oh, this :D

Would this also allow Bots to add form submission in HTML pages?

**Comment by mia-pi-git** [comment]
> Oh, this :D
> 
> Would this also allow Bots to add form submission in HTML pages?

It would allow bots to have users send commands to PS, yes.

**Comment by PartMan7** [comment]
Including ``/msg``?

**Comment by mia-pi-git** [comment]
> Including `/msg`?

Yes, any command, there are no client-side limits.

**Comment by Zarel** [comment]
Anyway, my main actual problem with this is in the syntax. The way I specified this was something like:

```html
<form data-submitsend="/nick {username}">
  <input name="username" />
  <button type="submit">Change name</button>
</form>
```

You seem to just loop through every element directly in the form and add its value with a comma. That would break utterly if you have anything but input elements in the form, such as paragraphs, or buttons...

**Comment by Zarel** [comment]
...ok we agreed on `data-submitsend` and this clearly uses `data-send` :s

**Comment by Zarel** [comment]
Also, an important thing to do is to clear the form after submitting (design standard D6). Otherwise people can accidentally send messages multiple times if they click twice.

Famous UX problem! https://thedailywtf.com/articles/Push-the-Button

**Comment by mia-pi-git** [comment]
> Also, an important thing to do is to something like close the form after submitting (design standard D6). Otherwise people can accidentally send messages multiple times if they click twice.
> 
> Famous UX problem! https://thedailywtf.com/articles/Push-the-Button

Huh. Thought I did that. Don't know if you're making more changes, do you want to make these two or shall I?

**Comment by Zarel** [comment]
I did them. Oh, also, general note: you should be using `getAttribute` rather than `attributes`.

**Comment by mia-pi-git** [comment]
> you should be using `getAttribute` rather than `attributes`.

Ah. Wish I knew about that earlier.

**Pull request merged**
