### PR TITLE
Update battle-animations.ts for battle crys in digimon mode

### PR DESCRIPTION
**Pull request by josephjoestar**
need to pass this.mod as argument in order for it to work

### CODE REVIEW

**Comment by Zarel** [comment]
Do you see that Travis build error?

**Comment by josephjoestar** [comment]
> Do you see that Travis build error?

Yep had it fixed

**Comment by Zarel** [comment]
Hm, it seems like having both `gen` and `mod` in the same call is probably unnecessary. I wonder if there's some way to merge them.

**Comment by josephjoestar** [comment]
do you think concatenating mod after gen. and splitting it after it is passed is a good idea?

**Comment by josephjoestar** [comment]
All the digimon have num<2000. Is it accepatable if I change
`	if (options.mod) {
			spriteData.cryurl = `sprites/${options.mod}/audio/${toID(template.baseSpecies)}`;
			spriteData.cryurl += (window.nodewebkit ? '.ogg' : '.mp3');
		}`

to
`if (pokemon.num<2000) {
			spriteData.cryurl = `sprites/digimon/audio/${toID(template.baseSpecies)}`;
			spriteData.cryurl += (window.nodewebkit ? '.ogg' : '.mp3');
		}``

and just get rid of mod

**Comment by Zarel** [comment]
Mod should already include gen, if you're using the correct format... PS's own mods probably need to be updated, though. :/

**Comment by josephjoestar** [comment]
as far as I checked the battlescene.mod was only set when battle.id.includes('digimon'). I wasn't aware there were any other uses outside of setting the audio for digimon.

**Comment by Zarel** [comment]
Well, I wish we had a better architecture, but I don't have time to design one, and this isn't too bad. I'll accept it as-is.

**Pull request merged**
