### PR TITLE
Tooltips: Halve Earthquake, Bulldoze BP in Grassy Terrain

### PR DESCRIPTION
**Pull request by DaWoblefet**
https://www.smogon.com/forums/threads/show-grassy-terrains-effect-on-the-3-ground-moves.3683343/

No point in displaying for Magnitude since it doesn't a base power anyway, since it can't be known before the turn and all.

### CODE REVIEW

**Comment by Zarel** [comment]
> No point in displaying for Magnitude since it doesn't a base power anyway, since it can't be known before the turn and all.

Why not? Magnitude should display a range, and `value.modify` will modify both ends of the range.

**Comment by Zarel** [comment]
Like if Magnitude _doesn't_ display "10-150 BP", it should, and `value.modify` is all you need to do to make it display "5-75 BP" instead.

**Comment by DaWoblefet** [comment]
> Like if Magnitude _doesn't_ display "10-150 BP", it should, and `value.modify` is all you need to do to make it display "5-75 BP" instead.

Excellent point!

image

**Comment by Zarel** [comment]
Thanks!

**Pull request merged**
