### PR TITLE
Fix old gen teambuilder bugs

### PR DESCRIPTION
**Pull request by Karthik99999**
Utilizes `Dex.getDescs` to get descriptions, since directly accessing `desc` or `shortDesc` doesn't seem to work.

### CODE REVIEW

**Comment by Karthik99999** [comment]
```js
if (this.battle.gen < 7 || this.battle.hardcoreMode) {
	text += '<p class="section">' + move.shortDesc + '</p>';
}
```
I just noticed this code snippet that prevents older gens from having long move descriptions. I feel like it could be beneficial to remove this now, considering I've gotten the long move descriptions to be overridden now.

**Comment by Karthik99999** [comment]
Decided to fix some more old gen teambuilder bugs. I fixed the move sorter and stat sorter, as well as made the proper abilities be displayed (examples below)

gen 1
image

gen 3 (main focus on gengar showing levitate, but also no hidden abilities)
image

**Comment by KrisXV** [comment]
In my opinion, pokemon with two abilities in gens 3/4 would look much nicer with ability 0 in the first column and ability 1 in the second column.

**Comment by Karthik99999** [comment]
> In my opinion, pokemon with two abilities in gens 3/4 would look much nicer with ability 0 in the first column and ability 1 in the second column.

I agree
image

**Comment by DaWoblefet** [comment]
Here's a list of all oldgen teambuilder bugs I have marked in the bug reports thread (I believe most, if not all, are fixed by this PR):
G- engar Cursed Body / Abilities being wrong in older gens - https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8473928, https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8662984, https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8759708, https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8786451
- Psychic in Gen 1- https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8602421
- The EV spread guesser uses modern gen for category - https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8596213, https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8771288
- BP ordering in Gen 5 with Keldeo - https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8621921
- Gen 1 displaying both Sp. Atk and Sp. Def - https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8623312
- Dexited moves are displayed as illegal on Smeargle in gens where it should be legal; e.g. Smeargle in Gen 5 OU with Judgment- https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8665121
- Duplicate Pokemon in oldgens if they are both in LC and in the "regular" tier - https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8540357, https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8532029, https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8747943
- Pokemon searching by stats use modern base stats rather than current gen - https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8771276
- Water Shuriken in Gen 6 - https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8754220, https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8829006
- Let's Go inheritance - https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8773561, https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8848760

**Comment by Karthik99999** [comment]
I don't believe Let's Go would be covered here, since that would be fixed with proper mod support.

**Comment by Zarel** [comment]
Thanks!

**Pull request merged**
