### PR TITLE
Fix AltFormPopup and setForm

### PR DESCRIPTION
**Pull request by Karthik99999**
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8871200

### CODE REVIEW

**Comment by Zarel** [comment]
Thanks!

**Comment by Zarel** [comment]
I wonder which change caused this problem. I know it worked in the past.

**Comment by Karthik99999** [comment]
it was during my Species/Move override refactor :P. I made `curTeam.dex` a thing cause the old overrides were being used in there, so this just made it easier to not have to use overrides in `client-teambuilder.js` + it's much more efficient than doing `Dex.forGen` every time. I just forgot to add the `room` property for `AltFormPopup` and `setForm` when I implemented it.

**Comment by Zarel** [comment]
Another bug that wouldn't have happened in TypeScript...

**Pull request merged**
