### PR TITLE
Add teambuilder support for Metronome Battle

### PR DESCRIPTION
**Pull request by KrisXV**

### CODE REVIEW

**Comment by KrisXV** [comment]
bump?

**Comment by Zarel** [comment]
rebase?

**Comment by KrisXV** [comment]
done @Zarel

**Comment by Zarel** [comment]
Do we actually need a table for just "metronome battles"?

**Comment by Zarel** [comment]
It's just, Metronome's legal, right?

**Comment by Zarel** [comment]
Oh, it has its own tiers?

**Comment by KrisXV** [comment]
it doesnt have its own tiers, but it requires its own teambuilder table because it allows every single Pokemon and the teambuilder currently display that, so a lot of users think the meta is Galar dex only.

**Comment by Zarel** [comment]
That shouldn't be a table, that should just be a setting in search.js to consider it a NatDex format.

**Comment by Zarel** [comment]
Or a hackable format.

**Comment by KrisXV** [comment]
I'm not sure what you mean. In search.js it is labeled as a natdex format, but more can be used than just natdex Pokemon. Not to mention the tiers for it are also used to filter out the bans

**Comment by Zarel** [comment]
I'm saying it's simple enough to hardcode rather than generating a teambuilder table for it.

**Comment by KrisXV** [comment]
There's also a plethora of banned items that could be added to a table. if i did that could the generated table stay? I don't really like the idea of hardcoding a teambuilder list for a format that constantly has changing bans.

**Comment by Zarel** [comment]
Oh, huh.

**Comment by Zarel** [comment]
That's annoying. The current systems aren't really set up for this sort of thing...

**Comment by Zarel** [comment]
Hey wait, there aren't even any teambuilder item tables in this PR. What are you actually trying to do?

**Comment by KrisXV** [comment]
There aren’t any because I forgot to add them. I can change that though

**Comment by KrisXV** [comment]
bump

**Comment by Zarel** [comment]
Sooner or later we need to genericize this code instead of piling on more special cases.

**Pull request merged**
