### PR TITLE
Handle Gigantamaxing properly

### PR DESCRIPTION
**Pull request by KrisXV**
i need help with sprites support before this or the server-side part of this (https://github.com/smogon/pokemon-showdown/pull/7001) gets merged @Zarel

### CODE REVIEW

**Comment by Zarel** [comment]
The best way for sprites support is to keep the dex entry. :p

**Comment by Zarel** [comment]
Like I mentioned in #sim-dev:

> the validator/simulator can convert it to a pikachu with the gmax flag before use
> convenience doesn't affect that

**Comment by Zarel** [comment]
I do think Gigantamaxing should just be `|-start|POKEMON|Dynamax|Gigantamax` though. I think that's possible to support on the client.

**Comment by KrisXV** [comment]
> I do think Gigantamaxing should just be |-start|POKEMON|Dynamax|Gigantamax though. I think that's possible to support on the client.
@Zarel I believe the gigantamax currently gets sent through a `-formechange`

**Comment by Zarel** [comment]
> @Zarel I believe the gigantamax currently gets sent through a `-formechange`

Yes, I'm saying it shouldn't. It's not a real forme change, and changing it to be a volatile flag better reflects how it works in-game, and should simplify our code, too.

**Comment by KrisXV** [comment]
Bump? @Zarel

**Comment by Zarel** [comment]
Looks good!

**Pull request merged**
